%YAML 1.2
---

path:
        services: /etc/systemdock/containers.d
        template: /usr/share/systemdock/templates/systemdock-container.service.template
        systemd: /usr/lib/systemd/system
container:
        start_timeout:  120
docker:
        base_url: unix:///var/run/docker.sock
        api_version: auto
        timeout: 10
logging:
        level: INFO
